# Generated by Django 3.0.6 on 2020-05-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('profile', '0009_auto_20200531_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='groups',
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(null=True, to='auth.Group'),
        ),
    ]
