# Generated by Django 3.0.6 on 2020-05-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='home/sergeybildin/Рабочий стол/DigitalProfile/DigitalProfile/DigitalProfile/static/media'),
        ),
        migrations.AddField(
            model_name='profile',
            name='institute',
            field=models.CharField(max_length=200, null=True, verbose_name='Подразделение/факультет/институт'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('St', 'Студент'), ('Org', 'Организатор')], default='St', max_length=50, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=20, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(max_length=200, null=True, verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.CharField(max_length=50, null=True, verbose_name='Номер группы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(max_length=300, null=True, verbose_name='навыки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(max_length=200, null=True, verbose_name='Напрвление/специальность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_study_date',
            field=models.DateField(null=True, verbose_name='Дата начала обучения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
