# Generated by Django 3.0.6 on 2020-05-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20200530_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Студент', 'Студент'), ('Организатор', 'Организатор')], default='Студент', max_length=50, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Мужской', 'Женский')], default='Мужской', max_length=20, verbose_name='Пол'),
        ),
    ]
