# Generated by Django 3.0.6 on 2020-05-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20200530_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='home/sergeybildin/Рабочий стол/DigitalProfile/DigitalProfile/DigitalProfile/static/media'),
        ),
    ]
