# Generated by Django 3.0.6 on 2020-05-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_auto_20200531_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill_groups',
            field=models.ManyToManyField(through='profile.Membership', to='profile.Groups'),
        ),
    ]
